/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MdReaderRouteImport } from './routes/md-reader'
import { Route as IndexRouteImport } from './routes/index'

const MdReaderRoute = MdReaderRouteImport.update({
  id: '/md-reader',
  path: '/md-reader',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/md-reader': typeof MdReaderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/md-reader': typeof MdReaderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/md-reader': typeof MdReaderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/md-reader'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/md-reader'
  id: '__root__' | '/' | '/md-reader'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MdReaderRoute: typeof MdReaderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/md-reader': {
      id: '/md-reader'
      path: '/md-reader'
      fullPath: '/md-reader'
      preLoaderRoute: typeof MdReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MdReaderRoute: MdReaderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
